spring:
  datasource:
    url: jdbc:h2:~/mydb
    username: sa
    password: 
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  jackson:
     default-property-inclusion: NON_NULL
logging:
  level:
    com.learning.java : DEBUG

            
